#!/bin/bash

#The MIT License (MIT)
#
#Copyright (c) 2013 drew
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files (the "Software"), to deal in
#the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
#the Software, and to permit persons to whom the Software is furnished to do so,
#subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
#FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
#IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
#CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


if [ $# -ne 2 ]
then
	echo Usage: mkdeb package_name package_directory
	exit 1
fi

PKG_FILE=$1
PKG_ROOT=$2
echo Creating $PKG_FILE out of $PKG_ROOT
mkdir $PKG_ROOT/DEBIAN
cp toolbox/debian/control $PKG_ROOT/DEBIAN
chmod 755 $PKG_ROOT -R
fakeroot dpkg-deb --build $PKG_ROOT $PKG_FILE
lintian $PKG_FILE
